version: '3.9'

services:
  pgadmin:
    container_name: pgadmin_user
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5434:80"
    depends_on:
      - postgres
